vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /uploads/images/products
            upload_destination: '%kernel.project_dir%/public/uploads/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        prestations:
            uri_prefix: /uploads/images/prestations
            upload_destination: '%kernel.project_dir%/public/uploads/images/prestations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
        companies:
            uri_prefix: /uploads/images/companies
            upload_destination: '%kernel.project_dir%/public/uploads/images/companies'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
